### ISSUE TITLE
ajout lieu dans le fichier events.json

### ISSUE THREAD

**Issue by brucelane** [lucj/sophia.events#10]
Bonjour,
est-il possible de rajouter un champ lieu?
j'ai mis en place l'affichage dynamique au Business Pôle, j'aimerais filtrer events.json pour n'afficher que les événements de ce lieu.
Merci,
Bruce

**Comment by lucj** [comment]
"location" field added in events.json
btw, events.json available on [https://sophia.events/events.json](https://sophia.events/events.json)

**Comment by brucelane** [comment]
merci Luc!
