### ISSUE TITLE
Dev mobile cote d'azur septembre

### ISSUE THREAD

**Issue by otusweb** [lucj/sophia.events#21]
"type: dmca
      title: Développement Mobile Côte-d'Azur,
      date: 5/9 à 18h30
      desc: Un meetup en collaboration avec le meetup AWS sur comment AWS peut vous aidez à vous simplifier la vie lors de la création de votre app.

• Olivier TOSELLO, viendra nous parler de AWS et notre appli mobile
• Michael Lopez et Stephane Martarello: Dimensionnement d'images à la volée avec AWS Lambda

**Comment by lucj** [comment]
Added.
Sorry for the delay, I need to automate the update of the json file some more :)
