### ISSUE TITLE
Google Hashcode 2018

### ISSUE THREAD

**Issue by mosser** [lucj/sophia.events#6]
In case you want to submit a new event, please make sure to provide the following information:

- Type of event: Code competition challenge
- Date: 01.03.2018
- Title: Google Hashcode @Polytech Nice-Sophia 
- Description: Hash Code is a team programming competition organized by Google for students and industry professionals across Europe, the Middle East and Africa. You pick your team and programming language, Google picks an engineering problem for you to solve.
- Link to the main event's web site: https://hashcode.withgoogle.com/signup.html
- Logo

**Comment by mosser** [comment]
It would be great if the event mention others hub than the Epitech one. There is (at least) one at Polytech in Sophia, and another one hosted by the CS dept of Valrose.

**Comment by lucj** [comment]
Added the Polytech one.
