### ISSUE TITLE
CLUSIR PACA / Côte d'Azur

### ISSUE THREAD

**Issue by Pat-Git2** [lucj/sophia.events#8]
<img src="https://www.clusir-paca.fr/wp-content/uploads/2016/01/logo-495x251.png" width=114 eight=58>
La prochaine réunion du CLUSIR PACA en territoire Côte d'Azur se réunira chez EURECOM le 12 mars 2018, de 18h30 à 20h.
Le thème abordé sera le suivant: "Le PIA : clé de voûte de votre conformité RGPD", par Edmond CISSE, URAEUS Consult.<p>

Toutes les infos et inscription gratuite sur: http://www.clusir-paca.fr/events/espace-rssi-9/

**Comment by ledroide** [comment]
@lucj voir PR #9

**Comment by lucj** [comment]
Added

**Comment by Pat-Git2** [comment]
Super, merci !
